// Generated by CoffeeScript 1.3.3
(function() {

  define(['underscore', 'backbone', 'text!templates/app.html'], function(_, Backbone, AppTemplate) {
    var App, AppRouter;
    App = {
      el: $('#tasksApp'),
      template: _.template(AppTemplate),
      router: null,
      tags: null,
      tasks: null,
      tagsView: null,
      tasksView: null,
      timelineView: null,
      statusBarView: null,
      init: function() {
        this.el.html(this.template());
        return require(['collections/tags', 'collections/tasks', 'views/tags', 'views/tasks', 'views/timeline', 'views/statusBar'], function(Tags, Tasks, TagsView, TasksView, TimelineView, StatusBarView) {
          App.tags = new Tags();
          App.tasks = new Tasks();
          App.tagsView = new TagsView({
            el: $("#tagsList")
          });
          App.tasksView = new TasksView({
            el: $("#tasks")
          });
          App.timelineView = new TimelineView({
            el: $("#timeline")
          });
          App.statusBarView = new StatusBarView({
            el: $("#statusBar")
          });
          return App.tags.fetch().done(function() {
            return App.tasks.fetch().done(App.onLoad);
          });
        });
      },
      onLoad: function() {
        App.router = new AppRouter();
        return Backbone.history.start();
      }
    };
    AppRouter = Backbone.Router.extend({
      routes: {
        'date/:date': 'date',
        'date/:date/tags/*tags': 'dateTags',
        'tags/*tags': 'tags'
      },
      date: function(date) {
        App.tasksView.setFilterDate(date);
        return App.tasksView.applyFilter();
      },
      dateTags: function(date, tags) {
        App.tasksView.setFilterDate(date);
        App.tasksView.addFilterTags(tags.split('/'));
        return App.tasksView.applyFilter();
      },
      tags: function(tags) {
        App.tasksView.addFilterTags(tags.split('/'));
        return App.tasksView.applyFilter();
      }
    });
    return App;
  });

}).call(this);
