// Generated by CoffeeScript 1.3.3
(function() {

  define(['underscore', 'backbone', 'app'], function(_, Backbone, App) {
    var StatusBarView;
    StatusBarView = Backbone.View.extend({
      events: {
        'click .updateTime': 'update'
      },
      updateTimestamp: 0,
      initialize: function() {
        var time;
        time = new Date();
        this.updateTime = this.$('.updateTime').text(this.formatTime(time));
        return this.updateTimestamp = Math.floor(time.getTime() / 1000);
      },
      formatTime: function(time) {
        var hours, minutes;
        hours = (time.getHours() < 10 ? '0' : '') + time.getHours();
        minutes = (time.getMinutes() < 10 ? '0' : '') + time.getMinutes();
        return hours + ':' + minutes;
      },
      update: function() {
        var time;
        App.tags.fetch({
          add: true,
          url: App.tags.url + '?ts=' + this.updateTimestamp
        });
        App.tasks.fetch({
          add: true,
          url: App.tasks.url + '?ts=' + this.updateTimestamp
        });
        time = new Date();
        this.updateTime.text(this.formatTime(time));
        return this.updateTimestamp = Math.floor(time.getTime() / 1000);
      }
    });
    return StatusBarView;
  });

}).call(this);
