// Generated by CoffeeScript 1.3.3
(function() {

  define(['underscore', 'backbone', 'app', 'views/tag'], function(_, Backbone, App, TagView) {
    var TagsView;
    TagsView = Backbone.View.extend({
      initialize: function() {
        App.tags.on('add', this.addOne, this);
        return App.tags.on('reset', this.addAll, this);
      },
      addOne: function(tag) {
        var idx, prevTag, view;
        view = new TagView({
          model: tag
        });
        idx = _.indexOf(App.tags.models, tag);
        if (idx <= 0) {
          return this.$el.prepend(view.render().el);
        } else {
          prevTag = App.tags.models[idx - 1].view.$el;
          return prevTag.after(view.render().el);
        }
      },
      addAll: function() {
        return App.tags.each(this.addOne, this);
      }
    });
    return TagsView;
  });

}).call(this);
