// Generated by CoffeeScript 1.3.3
(function() {

  define(['underscore', 'backbone', 'models/task'], function(_, Backbone, Task) {
    var Tasks;
    Tasks = Backbone.Collection.extend({
      model: Task,
      url: scriptUrl + '/api/tasks',
      comparator: function(a, b) {
        var a_weight, b_weight;
        a_weight = a.getWeight();
        b_weight = b.getWeight();
        if (a_weight === b_weight) {
          return 0;
        } else if (a_weight > b_weight) {
          return 1;
        } else if (a_weight < b_weight) {
          return -1;
        }
      },
      countByDay: function(taskIds) {
        var count;
        count = {};
        this.each(function(task) {
          var deadline;
          if (taskIds.length && _.indexOf(taskIds, task.id) === -1) {
            return;
          }
          deadline = task.get('deadline');
          if (count[deadline]) {
            return count[deadline]++;
          } else {
            return count[deadline] = 1;
          }
        });
        return count;
      }
    });
    return Tasks;
  });

}).call(this);
